### ISSUE TITLE
2.9. MeD: Bottom nav buttons: ARIA roles issues (1.3.1, 4.1.1, 4.1.2) module wide

### ISSUE THREAD

**Issue by Tamayuzu** [MeD-DMC/Snap-framework-MeD#26]

**Comment by farheenhalani** [comment]
Provide a valid value for the role attribute:
•	Make sure the value is spelled correctly.
•	Make sure the role value exists. (For example, a common mistake is to specify the invalid role "footer" when the valid role is "contentinfo".)
•	Make sure the role is not abstract.
For a list of valid ARIA roles, see Accessible Rich Internet Applications (WAI-ARIA) 1.1: Categorization of Roles. Note that some ARIA roles, while technically valid, are not widely supported by assistive technologies. This rule will fail when such roles are used.

**Comment by falcochip** [comment]
unique to SIWB snap course : : <nav role="change slide" class="backnext col-md-12" aria-label="Main Navigation" style="visibility: visible;"> 

snap framework: 
<nav class="backnext" aria-label="Main" style="visibility: visible;">
